apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-nginx-v2
  namespace: default
  labels:
    app: nginx2
    project: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ponetagon/cicd-nginx:v2
        ports:
        - containerPort: 80
#      imagePullSecrets:
#      - name: registry
#
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-nginx-v2
  namespace: default
  labels:
    app: nginx2
    project: cicd
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-nginx-v2
  namespace: default
spec:
  rules:
  - host: cicd-nginx.apps.olsdemo-rancher-new.openlandscape.cloud
    http:
      paths:
      - backend:
          service:
            name: cicd-nginx-v2
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cicd-nginx.apps.olsdemo-rancher-new.openlandscape.cloud
    secretName: openland-tls

